{% set name = "pyproximal" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyproximal-{{ version }}.tar.gz
  sha256: c3979e042c5324bbaaf4e19e80102cee6604a5eceec6350cdbe0445f4ccf1458

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - scipy >=1.11.0
    - pylops >=2.4.0
    - typing-extensions

test:
  imports:
    - pyproximal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PyLops/pyproximal
  summary: Python library implementing proximal operators to allow solving non-smooth, constrained convex problems with proximal algorithms.
  license: LGPL-3.0
  license_file: LICENSE.md
  dev_url: https://github.com/PyLops/pyproximal
  doc_url: https://pyproximal.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mrava87
    - mlondschien
